album_art_pattern = '^Folder\.(png|jpg|jpeg)$'

[[mount_dirs]]
name = 'root'
source = 'test-data/small-collection'

[[users]]
name = 'test_user'
initial_password = 'very_secret_password'
admin = true
