[settings]
album_art_pattern = '^Folder\.(png|jpg|jpeg)$'

[[settings.mount_dirs]]
name = 'root'
source = 'test-data/small-collection'

[[users]]
name = 'test_user'
password = 'very_secret_password'
admin = true
